# Generated by Django 5.2.6 on 2025-09-25 19:08

import video_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Short display title', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional description')),
                ('file', models.FileField(help_text='Upload the original video file', upload_to=video_app.models.video_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
                'ordering': ('-created_at',),
            },
        ),
    ]
