# Generated by Django 5.2.6 on 2025-09-28 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='category',
            field=models.CharField(default='Uncategorized', help_text='Category/genre of the video', max_length=100),
        ),
    ]
