# Generated by Django 5.2.6 on 2025-09-28 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0002_video_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.CharField(blank=True, help_text='Category/genre of the video', max_length=100, null=True),
        ),
    ]
