# Generated by Django 5.2.6 on 2025-10-12 11:54

import video_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0003_alter_video_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Optional thumbnail image', null=True, upload_to=video_app.models.thumbnail_upload_path),
        ),
    ]
